# Generated by Django 3.1.2 on 2020-12-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Palasia, Indore', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(default='9898989898', max_length=10),
        ),
    ]
