# Generated by Django 3.1.3 on 2020-11-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0003_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_added']},
        ),
    ]
